#!/usr/bin/env bash
# Tells a story based on the contents of '/etc/passwd' file.
while IFS=':' read -r username password uid gid info home shell;
do
   echo "The user $username is part of the $gid gang."\
   "lives in $home and rides $shell."\
   "$uid's place is prtected by the passcode,"\
   "more info  abput the user here: $info"
done < "/etc/passwd"
