#!/usr/bin/env bash
# A script that displays a list of currently running processes
# Displays all processes, for all users, including those without a TTY
# Displays in a user-oriented format
# Shows process hierarchy

ps -u -a -x -f 
