#!/usr/bin/env bash
# A script to do the following:
# Creates a file containing its PID
# Displays to infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINTG signal
# Deletes the file and terminates itself when receiving a SiGQUIT or SIGTERM signal

file="/var/run/myscript.pid"

if [ ! -e "$file" ]; then
	touch "$file"
fi
sleep 2 &
echo "$!" > "$file"

trap 'echo "I hate the kill command"; rm "$file"; exit' SIGTERM SIGQUIT

trap "echo Y U no love me?!" SIGINT

while true; do
	echo "To infinity and beyond"
	sleep 2
done
