#!/usr/bin/env bash
# A script that
# Creates a file containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file and terminates itself when receiving a SIGQUIT or SIGTERM signal

file="/var/run/myscript.pid"
echo ps > "$file"

while true; do
	echo "To infinity and beyond"
	sleep 2
done

trap 'echo "I hate the kill command"; rm "$file"; exit' 15 SIGQUIT

trap "echo Y U no love me?!" SIGINT
